shop/order/urls.py
from django.urls import path
from .views import add_to_cart, updateCountItem, removItemCart, cartView

app_name = 'order'

urlpatterns = [
	path('add_to_cart/', add_to_cart, name="add_to_cart"),
	path('update_count_item/<int:product_id>/', updateCountItem, name="update_count_item"),
	path('remove_item_cart/<int:product_id>/', removItemCart, name="remove_item_cart"),
	path('cart/', cartView, name="cart"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('product.urls')),
    path('', include('order.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/order/models.py
from django.db import models
from account.models import User
from product.models import Product


class Order(models.Model):
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	is_paid = models.BooleanField(verbose_name='پرداخت شده / نشده', default=False)
	payment_date = models.DateTimeField(verbose_name='تاریخ پرداخت', blank=True, null=True)

	class Meta:
		verbose_name = 'سبد خرید'
		verbose_name_plural = 'سبد های خرید'

	def __str__(self):
		return self.owner.username

	def get_total_price_order(self):
		amount = 0
		for item in self.orderdetail_set.all():
			amount += item.price * item.count
		return amount


class OrderDetail(models.Model):
	order = models.ForeignKey(Order,on_delete=models.CASCADE, verbose_name='سبد خرید')
	product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
	price = models.IntegerField(verbose_name='قیمت محصول')
	count = models.IntegerField(verbose_name='تعداد', default=1)

	class Meta:
		verbose_name = 'جزیئات محصول'
		verbose_name_plural = 'جزیئات محصولات'

	def __str__(self):
		return self.product.title

	def get_total_price(self):
		return self.price * self.count

shop/order/forms.py
from django import forms


class AddToOrderForm(forms.Form):
	product_id = forms.IntegerField(widget=forms.HiddenInput)
	count = forms.IntegerField(
		widget=forms.NumberInput(attrs={'class': 'form-control'}),
		label='تعداد'
	)

	def clean_count(self):
		count = self.cleaned_data.get('count')

		if count < 0:
			count = 1

		return count

shop/order/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import FormView, TemplateView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib import messages
from django.core.exceptions import ValidationError
from .models import Order, OrderDetail
from .forms import AddToOrderForm
from product.models import Product


@login_required
def add_to_cart(request):
	order_form = AddToOrderForm(request.POST or None, initial={'count': 1})

	if request.method == 'POST':
		if order_form.is_valid():
			order = Order.objects.filter(owner_id=request.user.id, is_paid=False).first()
			if order is None:
				order = Order.objects.create(owner_id=request.user.id, is_paid=False)

			product_id = order_form.cleaned_data.get('product_id')
			count = order_form.cleaned_data.get('count')
			product = Product.objects.get(id=product_id)

			# Todo: Check product already added to order detail
			qs = OrderDetail.objects.filter(product_id=product.id, order_id=order.id)
			if qs.exists():
				print(count)
				for item in qs:
					stock_count = item.product.stock_count

					if count > stock_count:
						messages.add_message(request, messages.ERROR, 'تعداد خرید شما بزرگ تر از موجودی محصول می باشد. لطفا عدد درست وارد نمایید.')
						return redirect(reverse('product:detail', kwargs={'pk': product_id}))
					else:
						item.count += count
						item.product.stock_count -= count
						item.product.save()
					
					item.save()
						
			else:
				# this check discount and price
				price_final = 0
				if product.discount > 0:
					price_final = product.discount
				else:
					price_final = product.price
				
				# this check product stock count
				if count > product.stock_count:
					messages.add_message(request, messages.INFO, 'تعداد خرید شما بزرگ تر از موجودی محصول می باشد. لطفا عدد درست وارد نمایید.')
					return redirect(reverse('product:detail', kwargs={'pk': product_id}))
				else:
					print('count', count)
					if count > 1:
						product.stock_count -= count
					else:
						product.stock_count -= 1
					product.save()
				print('f', count)

				order.orderdetail_set.create(
					product_id=product.id,
					price=price_final,
					count=count
				)
			print(qs, qs.exists())
			# return qs

			return redirect(reverse('product:detail', kwargs={'pk': product_id}))

	return render(reverse('order:cart'))


@login_required
def updateCountItem(request, product_id):
	order: Order = Order.objects.filter(owner_id=request.user.id, is_paid=False).first()
	qs = OrderDetail.objects.filter(product_id=product_id, order_id=order)

	if request.method == 'POST':
		if qs.exists():
			count = request.POST.get('count')
			if int(count) < 0 or int(count) == 0:
				count = 1
			for item in qs:
				
				print('value', count)
				if int(count) > item.product.stock_count:
					# print('this check')
					# print('count now', count)
					messages.add_message(request, messages.ERROR, 'تعداد خرید شما بزرگ تر از موجودی محصول می باشد. لطفا عدد درست وارد نمایید.')
					return redirect(reverse('order:cart'))
				else:
					if int(count) > 1:
						# print('01 ',count)
						item.product.stock_count -= int(count)
						item.product.save()
					else:
						# print('02', count)
						item.product.stock_count -= 1
						item.product.save()
				# print('f', count)
				item.count += int(count)
				item.save()

	order.orderdetail_set.all()
	return redirect(reverse('order:cart'))


@login_required
def removItemCart(request, product_id):
	# print(order_id)
	order: Order = Order.objects.filter(owner_id=request.user.id, is_paid=False).first()
	qs = OrderDetail.objects.filter(product_id=product_id, order_id=order.id)

	# result = order.orderdetail_set.product
	items = order.orderdetail_set.all()
	for item in items:
		if product_id == item.id:
			item.product.stock_count += item.count
			item.count = 0
			item.product.save()
			item.save()
			item.delete()
			# print(request.session.get('count'))
			
			return redirect(reverse('order:cart'))
		print('product id', product_id)
		print('item id', item.id)

	return redirect(reverse('product:home'))


def cartView(request):
	context = {
		'order': None,
		'orderdetails': None,
		'total': 0
	}
	order: Order = Order.objects.filter(owner_id=request.user.id, is_paid=False).first()

	if order is not None:
		context['order'] = order
		context['orderdetails'] = order.orderdetail_set.all()
		context['total'] = order.get_total_price_order()

	return render(request, 'order/cart.html', context)

shop/order/templates/order/_messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
    {{ message }}
    </div>
    {% endfor %}
{% endif %}

shop/order/templates/order/add_to_cart.html
{{ form }}

shop/order/templates/order/cart.html
{% extends 'product/base.html' %}

{% block title %} {% endblock %}
{% block ref_css %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

<style>
    .alert-error {
    color: #842029;
    background-color: #f8d7da;
    border-color: #f5c2c7;
}
</style>


{% endblock %}


{% block content %}

<div class="container padding-bottom-3x mb-1">

    <!-- Shopping Cart-->
    <div class="table-responsive shopping-cart">
        {% include 'order/_messages.html' %}

        {% if order != None and orderdetails|length > 0 %}
            <table class="table">
            <thead>
            <tr>
                <th>تصویر محصول</th>
                <th>عنوان محصول</th>
                <th class="text-center">تعداد</th>
                <th class="text-center">قیمت</th>
                <th class="text-center">مجمع</th>
                <th class="text-center">تعداد موجود</th>
                <th class="text-center">حذف</th>
            </tr>
            </thead>
            <tbody>
            {% for detail in orderdetails %}
            <tr>
                
                <td>
                    <div class="product-item">
                        <a class="product-thumb" href="#">
                            <img src="{{ detail.product.thumbnail.url }}"
                                 alt="Product" width="80" height="80"></a>
                    </div>
                </td>
                <td>
                    <div class="product-info">
                        <h4 class="product-title" style="font-size: 14px;">{{ detail.product.title }}</h4>
                    </div>
                </td>
                <td class="text-center">
                    {% if detail.product.stock_count > 0 %}
                    <div class="count-input">
                        <form action="{% url 'order:update_count_item' detail.product.id %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="product_id" value="{{ detail.product.id }}">
                            <input type="number" class="form-control" style="width: 80px;display:inline-block;" name="count" value="1">
                            <span>{{ detail.count }}</span>
                            <button type="submit" class="btn btn-success btn-sm">ویرایش</button>
                        </form>
                    </div>
                        {% else %}
                            <span>{{ detail.count }}</span>
                    {% endif %}
                </td>
                <td class="text-center text-lg text-medium">{{ detail.price }}</td>
                <td class="text-center text-lg text-medium">{{ detail.get_total_price }}</td>
                <td class="text-center text-lg text-medium">{{ detail.product.stock_count }}</td>
                <td class="text-center">
                    <a class="remove-from-cart" href="{% url 'order:remove_item_cart' detail.id %}"><i class="fa fa-trash"></i></a>
                </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p>شما هنوز هیچ محصولی در سبد خرید وجود ندارد.</p>
        {% endif %}
    </div>
    <div class="shopping-cart-footer">

        <div class="column text-lg">جمع کل قیمت: <span class="text-medium">{{ total }} تومان</span></div>
    </div>
    <div class="shopping-cart-footer">
        <br>
        <div class="column">
            <a href="#" class="btn btn-primary">پرداخت نهایی</a>
        </div>
    </div>
</div>
{% endblock %}