shop/account/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, logoutUser, activate

app_name = 'account'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name="register"),
    path('login/', UserLoginView.as_view(), name="login"),
    path('logout/', logoutUser, name="logout"),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
]

shop/order/urls.py
from django.urls import path
from .views import add_to_cart, updateCountItem, removItemCart, cartView

app_name = 'order'

urlpatterns = [
	path('add_to_cart/', add_to_cart, name="add_to_cart"),
	path('update_count_item/<int:product_id>/', updateCountItem, name="update_count_item"),
	path('remove_item_cart/<int:product_id>/', removItemCart, name="remove_item_cart"),
	path('cart/', cartView, name="cart"),
]

shop/product/urls.py
from django.urls import path
from .views import (
	ProductListHomeView,
	ProductListView,
	ProductDetailView,
	ProductCreateView,
	ProductUpdateView,
	ProductDeleteView,
	GalleryListView,
	GalleryCreateView,
	GalleryUpdateView,
	GalleryDeleteView,
)

app_name = "product"

urlpatterns = [
	path('', ProductListHomeView.as_view(), name="home"),
	path('product_list/', ProductListView.as_view(), name="product_list"),
	path('product/<int:pk>/', ProductDetailView.as_view(), name="detail"),
	path('product_create/', ProductCreateView.as_view(), name="product_create"),
	path('product_update/<int:pk>', ProductUpdateView.as_view(), name="product_update"),
	path('product_delete/<int:pk>', ProductDeleteView.as_view(), name="product_delete"),
]

urlpatterns += [
	path('gallery_list/', GalleryListView.as_view(), name="gallery_list"),
	path('gallery_create/', GalleryCreateView.as_view(), name="gallery_create"),
	path('gallery_update/<int:pk>', GalleryUpdateView.as_view(), name="gallery_update"),
	path('gallery_delete/<int:pk>', GalleryDeleteView.as_view(), name="gallery_delete"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('product.urls')),
    path('', include('order.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/product/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
from django.conf import settings
import os
from PIL import Image
from uuid import uuid4


class Product(models.Model):
	title = models.CharField(max_length=254, verbose_name='عنوام محصول')
	text = models.TextField(verbose_name='توضیحات محصول')
	price = models.BigIntegerField(verbose_name='قیمت', default=0)
	discount = models.BigIntegerField(verbose_name='قیمت با تخفیف', default=0)
	image = models.ImageField(verbose_name='تصویر', upload_to='product/images/')
	thumbnail = models.ImageField(upload_to='product/images/', blank=True, null=True)
	stock_count = models.IntegerField(verbose_name='تعداد موجودی', default=1)
	sell_count = models.IntegerField(verbose_name='تعداد به فروش رفته', default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'محصول'
		verbose_name_plural = 'محصولات'


class GalleryProduct(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='galleries')
	images = models.ImageField(verbose_name='تصویر', upload_to='product/galleries/')

	def __str__(self):
		return self.product.title

	class Meta:
		verbose_name = 'گالری'
		verbose_name_plural = 'گالری ها'


# *********************** Section for model Product ***********************
@receiver(pre_save, sender=Product)
def pre_save_product(sender, instance, **kwargs):

	# ********** Section resize image ***********
	image = Image.open(instance.image)
	resized_image = image.resize((400, 400))
	fileName = "%s.%s" % (uuid4(), image.format)
	filePath = f"{settings.MEDIA_ROOT}/product/images/{fileName}"
	instance.thumbnail = f"product/images/{fileName}"
	resized_image.save(filePath)

	# ********** this section for remove old image ***************
	print(instance.pk)
	if instance.pk:
		try:
			old_product_image = Product.objects.get(pk=instance.pk).image
			old_product_thumbnail = Product.objects.get(pk=instance.pk).thumbnail
		except Product.DoesNotExist:
			return False

		new_product_image = instance.image
		new_product_thumbnail = instance.thumbnail
		print(new_product_image)
		print(new_product_thumbnail)
		if old_product_image and old_product_image.url != new_product_image.url and old_product_thumbnail \
			and old_product_thumbnail.url != new_product_thumbnail.url:
			os.remove(old_product_image.path)
			os.remove(old_product_thumbnail.path)

@receiver(pre_delete, sender=Product)
def pre_delete_product(sender, instance, **kwargs):
	object_current = sender.objects.get(pk=instance.pk)

	if object_current:
		os.remove(object_current.image.path)
		os.remove(object_current.thumbnail.path)


# *********************** Section for model GalleryProduct ***********************
@receiver(pre_delete, sender=GalleryProduct)
def pre_delete_gallery_product(sender, instance, **kwargs):
	object_current = sender.objects.get(pk=instance.pk)

	if object_current:
		os.remove(object_current.images.path)


@receiver(pre_save, sender=GalleryProduct)
def pre_save_gallery_product(sender, instance, **kwargs):

	if instance.pk:
		try:
			old_gallery_image = GalleryProduct.objects.get(pk=instance.pk).images
		except GalleryProduct.DoesNotExist:
			return False

		new_gallery_image = instance.images
		if old_gallery_image and old_gallery_image.url != new_gallery_image.url:
			os.remove(old_gallery_image.path)

shop/product/forms.py
from django import forms
from .models import Product, GalleryProduct


class ProductForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	class Meta:
		model = Product
		fields = ('title', 'text', 'price', 'discount', 'image', 'stock_count')

	def clean_discount(self):
		price = self.cleaned_data.get('price')
		discount = self.cleaned_data.get('discount')

		if discount < price:
			return discount
		raise forms.ValidationError('قیمت با تخفیف باید از قیمت اصلی محصول کوچک تر باشد.')

	def clean_price(self):
		price = self.cleaned_data.get('price')
		if price < 0 or price == 0:
			raise forms.ValidationError('لطفا یک قیمت درست وارد کنید.')

		return price

	def clean_stock_count(self):
		stock_count = self.cleaned_data.get('stock_count')
		if stock_count == 0 or stock_count < 0:
			raise forms.ValidationError('لطفا تعداد موجودی درست وارد نمایید.')

		return stock_count


class GalleryProductForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	image = forms.FileField(
		widget=forms.ClearableFileInput(attrs={
			'multiple': True
		}),
		required=True
	)

	class Meta:
		model = GalleryProduct
		fields = ('product', 'image')


class GalleryUpdateProductForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	class Meta:
		model = GalleryProduct
		fields = ('product', 'images')

shop/product/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.forms import inlineformset_factory, formset_factory, modelformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
	ListView,
	CreateView,
	UpdateView,
	DeleteView,
	DetailView,
)
from .models import Product, GalleryProduct
from .forms import ProductForm, GalleryProductForm, GalleryUpdateProductForm
from order.forms import AddToOrderForm
from order.models import Order, OrderDetail


# ********************* Section for Product Model *********************
class ProductListHomeView(ListView):
	model = Product
	template_name = 'product/product_list.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		if self.request.user.is_authenticated:
			order = Order.objects.filter(owner_id=self.request.user.id, is_paid=False).first()
			if order is not None:
				count = order.orderdetail_set.count()
				self.request.session['count'] = count
				if count > 0:
					if self.request.session.has_key('count'):
						self.request.session['count'] = count
					else:
						self.request.session['count'] = 0
				self.request.session['count'] = count
						
				context['count'] = count

		return context


class ProductDetailView(DetailView):
	model = Product
	template_name = 'product/product_detail.html'
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		# check count items
		if self.request.user.is_authenticated:
			order = Order.objects.filter(owner_id=self.request.user.id, is_paid=False).first()
			if order is not None:
				count = order.orderdetail_set.count()
				self.request.session['count'] = count
				if count > 0:
					if self.request.session.has_key('count'):
						self.request.session['count'] = count
					else:
						self.request.session['count'] = 0
				self.request.session['count'] = count

		product = kwargs.get('object')
		context['order_form'] = AddToOrderForm(self.request.POST or None, initial={'product_id': product.id, 'count': 1})
		return context


class ProductCreateView(LoginRequiredMixin, CreateView):
	model = Product
	form_class = ProductForm
	template_name = 'product/product_create.html'

	def form_valid(self, form):
		response = form.save(commit=False)
		context = {
			'form': form
		}
		if form.is_valid():
			title = form.cleaned_data.get('title')
			text = form.cleaned_data.get('text')
			image = form.cleaned_data.get('image')
			price = form.cleaned_data.get('price')
			discount = form.cleaned_data.get('discount')
			stock_count = form.cleaned_data.get('stock_count')

			Product.objects.create(
				title=title,
				text=text,
				image=image,
				price=price,
				discount=discount,
				stock_count=stock_count
			)
			messages.add_message(self.request, messages.SUCCESS, 'محصول شما با موفقیت ایجاد شد.')

		return render(self.request, self.template_name, context)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
	model = Product
	form_class = ProductForm
	template_name = 'product/product_create.html'
	success_url = reverse_lazy('product:home')


class ProductDeleteView(LoginRequiredMixin, DeleteView):
	model = Product
	template_name = 'product/product_confirm_delete.html'
	success_url = reverse_lazy('product:product_list')


class ProductListView(LoginRequiredMixin, ListView):
	model = Product
	template_name = 'product/list_product.html'


# ********************* Section for Gallery Model *********************
class GalleryListView(LoginRequiredMixin, ListView):
	model = GalleryProduct
	template_name = 'gallery/gallery_list.html'


class GalleryCreateView(LoginRequiredMixin, CreateView):
	model = GalleryProduct
	form_class = GalleryProductForm
	template_name = 'gallery/gallery_create.html'

	def post(self, request, *args, **kwargs):
		form_class = self.form_class
		form = self.get_form(form_class)
		context = {
			'form': form
		}

		if form.is_valid():
			product = form.cleaned_data.get('product')
			images = request.FILES.getlist('image')
			for image in images:
				GalleryProduct.objects.create(
					product=product,
					images=image
				)
			messages.add_message(request, messages.SUCCESS, 'گالری شما با موفقیت ایجاد شد.')
			print(product)
			print(images)

		return render(request, self.template_name, context)


class GalleryUpdateView(LoginRequiredMixin, UpdateView):
	model = GalleryProduct
	form_class = GalleryUpdateProductForm
	template_name = 'gallery/gallery_update.html'
	success_url = reverse_lazy('product:home')


class GalleryDeleteView(LoginRequiredMixin, DeleteView):
	model = GalleryProduct
	success_url = reverse_lazy('product:gallery_list')
	template_name = 'gallery/galleryproduct_confirm_delete.html'

shop/product/templates/product/_messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

shop/product/templates/product/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}Shop management{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'product/assets/favicon.ico' %}"/>
    <!-- Bootstrap icons-->
<!--    <link href="{% static 'product/css/bootstrap-icons.css' %}" rel="stylesheet"/>-->
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>-->
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'product/css/styles.css' %}" rel="stylesheet"/>
    {% block ref_css %}{% endblock %}
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'product:home' %}">مدیریت فروشگاه</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto mb-2 mb-lg-0 ms-lg-4">

                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'product:home' %}">صفحه اصلی</a></li>

                    {% if request.user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                            data-bs-toggle="dropdown">مدریت فروشگاه</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'product:product_list' %}">لیست محصولات</a></li>
                                <li><a class="dropdown-item" href="{% url 'product:product_create' %}">افزودن محصول جدید</a></li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                            data-bs-toggle="dropdown">مدریت گالری</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'product:gallery_list' %}">لیست گالری ها</a></li>
                                <li><a class="dropdown-item" href="{% url 'product:gallery_create' %}">افزودن گالری جدید</a></li>
                            </ul>
                        </li>
                    {% endif %}

                </ul>
            </div>

             <ul class="navbar-nav ml-auto ">
                 <li>
                    <a class="btn btn-outline-dark ml-5" href="{% url 'order:cart' %}">
                        <i class="bi-cart-fill me-1"></i>
                        سبد
                        <span class="badge bg-dark text-white ms-1 rounded-pill ml-5">{{ request.session.count }}</span>
                    </a>
                 </li>

                {% if request.user.is_authenticated %}
                    <li class="nav-item mr-5" style="margin-left: 10px;"><a class="nav-link btn btn-warning btn-sm" href="{% url 'account:logout' %}">خروج</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">{{ request.user.get_full_name }}</a></li>
                    {% else %}
                    <li class="nav-item mr-5" style="margin-left: 10px;"><a class="nav-link btn btn-info btn-sm" href="{% url 'account:login' %}">ورود</a></li>
                    <li class="nav-item mr-5" style="margin-left: 10px;"><a class="nav-link btn btn-primary btn-sm" href="{% url 'account:register' %}">ثبت نام</a></li>
                {% endif %}
                
                
            </ul>

        </div>
    </nav>
    {% block main_header %}{% endblock %}
    <!-- Section-->
    <section class="py-5">
        {% block content %}{% endblock %}
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="{% static 'product/js/jquery.js' %}"></script>
    <script src="{% static 'product/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core theme JS-->
    <script src="{% static 'product/js/scripts.js' %}"></script>
    {% block ref_js %}{% endblock %}
</body>
</html>

shop/product/templates/product/list_product.html
{% extends 'product/base.html' %}

{% block title %} صفحه اصلی | مدیریت فروشگاه {% endblock %}


{% block content %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">تصویر</th>
                <th scope="col">عنوان</th>
                <th scope="col">قیمت</th>
                <th scope="col">قیمت با تخفیف</th>
                <th scope="col">تعداد موجود</th>
                <th scope="col">تعداد به فروش رفته</th>
                <th scope="col">تاریخ انتشار</th>
                <th scope="col">عملیات</th>
            </tr>
            </thead>
            <tbody>
            {% for product in object_list %}
             <tr>
                <th scope="row">{{ product.pk }}</th>
                <td>
                    <img src="{{ product.thumbnail.url }}" width="60" height="60" style="border-radius: 200px;">
                </td>
                <td>
                    <a href="#">{{ product.title }}</a>
                </td>
                <td>{{ product.price }}</td>
                <td>{{ product.discount }}</td>
                <td>{{ product.stock_count }}</td>
                <td>{{ product.sell_count }}</td>
                <td>{{ product.created_at|date:"Y d m" }}</td>
                <td>
                    <a href="{% url 'product:product_delete' product.pk %}" class="btn btn-danger btn-sm">حذف</a>
                    <a href="{% url 'product:product_update' product.pk %}" class="btn btn-info btn-sm">ویرایش</a>
                </td>
            </tr>
            {% endfor %}


            </tbody>
        </table>

    </div>
</div>
{% endblock %}

shop/product/templates/product/product_confirm_delete.html
<form method="post">{% csrf_token %}

<p>آیا از حذف این محصول مطمئن هستید ؟ "{{ object }}"?</p>

    <input type="submit" value="تایئد">
</form>

shop/product/templates/product/product_create.html
{% extends 'product/base.html' %}

{% block title %} ایجاد محصول جدید | مدیریت فروشگاه {% endblock %}

{% block content %}
<!-- Product section-->
<section class="py-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="fw-bolder text-center text-info mb-5">ایجاد محصول جدید</h1>
                <hr>
                {% include 'product/_messages.html' %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="mb-3">
                        <label for="{{ form.title.id_for_label }}" class="form-label">عنوان محصول: </label>
                        {{ form.title }}
                        {{ form.title.errors }}
                    </div>
                        <div class="mb-3">
                            <label for="{{ form.text.id_for_label }}" class="form-label">توضحیات محصول: </label>
                            {{ form.text }}
                            {{ form.text.errors }}
                        </div>
                        <div class="col-12 col-md-6 mb-3">
                            <label for="{{ form.price.id_for_label }}" class="form-label">قیمت محصول: </label>
                            {{ form.price }}
                            {{ form.price.errors }}
                        </div>
                        <div class="col-12 col-md-6 mb-3">
                            <label for="{{ form.discount.id_for_label }}" class="form-label">قیمت با تخفیف محصول: </label>
                            {{ form.discount }}
                            {{ form.discount.errors }}
                        </div>
                        <div class="col-12 col-md-6 mb-3">
                            <label for="{{ form.image.id_for_label }}" class="form-label">تصویر محصول: </label>
                            {{ form.image }}
                            {{ form.image.errors }}
                        </div>
                        <div class="col-12 col-md-6 mb-3">
                            <label for="{{ form.stock_count.id_for_label }}" class="form-label">تعداد موجود محصول: </label>
                            {{ form.stock_count }}
                            {{ form.stock_count.errors }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success w-100">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/product/templates/product/product_detail.html
{% extends 'product/base.html' %}

{% block title %} صفحه جزیئات محصول | مدیریت فروشگاه {% endblock %}

{% block ref_css %}
<style>
    .alert-error {
    color: #842029;
    background-color: #f8d7da;
    border-color: #f5c2c7;
}
</style>

{% endblock ref_css %}



{% block content %}
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6">
                {% include 'product/_messages.html' %}

                <img class="card-img-top mb-5 mb-md-0" src="{{ object.thumbnail.url }}" alt="{{ object.title }}"/>
                <!-- Gallery -->
                {% if object.galleries.all %}
                    <div id="gallery">
                        {% for gallery in object.galleries.all %}
                        <img src="{{ gallery.images.url }}" alt="{{ gallery.product.title }}" width="120" height="120">
                        {% endfor %}
                    </div>
                {% else %}
                        <p>این محصول هیچ گالری تصویری ندارد.</p>
                {% endif %}
            </div>
            <div class="col-md-6">
                <h1 class="display-5 fw-bolder">{{ object.title }}</h1>
                <div class="fs-5 mb-5">
                    {% if object.discount > 0 %}
                        <span class="text-decoration-line-through">{{ object.price }}</span>
                        <span>{{ object.discount }}</span>
                        {% else %}
                        <span>{{ object.price }}</span>
                    {% endif %}
                </div>
                <div class="fs-5 mb-5">
                    {% if object.stock_count > 0 %}
                        <span>تعداد موجود: {{ object.stock_count }}</span>
                        {% else %}
                        <span>تعداد موجود: تمام محصول</span>
                    {% endif %}
                </div>
                <div class="d-flex">
                    {% if object.stock_count > 0 %}
                        <form action="{% url 'order:add_to_cart' %}" method="post">
                            {%  csrf_token %}
                            {{ order_form.product_id }}
                            <div class="form-group">
                                <label for="{{ order_form.count.id_for_label }}">تعداد: </label>
                                {{ order_form.count }}
                            </div>
                            <button type="submit" class="btn btn-primary">اضافه کردن به سبد</button>
                        </form>
                    {% endif %}
                </div>
                <br>
                {{ object.text|safe }}
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/product/templates/product/product_list.html
{% extends 'product/base.html' %}

{% block title %} صفحه اصلی | مدیریت فروشگاه {% endblock %}

{% block main_header %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">مدیریت فروشگاه</h1>
            <p class="lead fw-normal text-white-50 mb-0">ساخت شده با جنگو</p>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for product in object_list %}
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Sale badge-->
                <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale
                </div>
                <!-- Product image-->
                <img class="card-img-top" width="400" height="250" src="{{ product.thumbnail.url }}" alt="{{ product.title }}"/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <a href="{% url 'product:detail' product.pk %}">
                            <h5 class="fw-bolder">{{ product.title }}</h5>
                        </a>

                        <!-- Product price-->
                        {% if product.discount > 0 %}
                            <span class="text-muted text-decoration-line-through">{{ product.price }}</span>
                            {{ product.discount }}
                            {% else %}
                            {{ product.price }}
                        {% endif %}
                        <hr>
                        <p>موجودی : {{ product.stock_count }}</p>
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product:detail' product.id %}">مشاهده محصول</a></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}