shop/product/urls.py
from django.urls import path
from .views import (
	ProductListHomeView,
	ProductListView,
	ProductDetailView,
	ProductCreateView,
	ProductUpdateView,
	ProductDeleteView,
	GalleryListView,
	GalleryCreateView,
	GalleryUpdateView,
	GalleryDeleteView,
)

app_name = "product"

urlpatterns = [
	path('', ProductListHomeView.as_view(), name="home"),
	path('product_list/', ProductListView.as_view(), name="product_list"),
	path('product/<int:pk>/', ProductDetailView.as_view(), name="detail"),
	path('product_create/', ProductCreateView.as_view(), name="product_create"),
	path('product_update/<int:pk>', ProductUpdateView.as_view(), name="product_update"),
	path('product_delete/<int:pk>', ProductDeleteView.as_view(), name="product_delete"),
]

urlpatterns += [
	path('gallery_list/', GalleryListView.as_view(), name="gallery_list"),
	path('gallery_create/', GalleryCreateView.as_view(), name="gallery_create"),
	path('gallery_update/<int:pk>', GalleryUpdateView.as_view(), name="gallery_update"),
	path('gallery_delete/<int:pk>', GalleryDeleteView.as_view(), name="gallery_delete"),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('product.urls')),
    path('', include('order.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/product/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
from django.conf import settings
import os
from PIL import Image
from uuid import uuid4


class Product(models.Model):
	title = models.CharField(max_length=254, verbose_name='عنوام محصول')
	text = models.TextField(verbose_name='توضیحات محصول')
	price = models.BigIntegerField(verbose_name='قیمت', default=0)
	discount = models.BigIntegerField(verbose_name='قیمت با تخفیف', default=0)
	image = models.ImageField(verbose_name='تصویر', upload_to='product/images/')
	thumbnail = models.ImageField(upload_to='product/images/', blank=True, null=True)
	stock_count = models.IntegerField(verbose_name='تعداد موجودی', default=1)
	sell_count = models.IntegerField(verbose_name='تعداد به فروش رفته', default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'محصول'
		verbose_name_plural = 'محصولات'


class GalleryProduct(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='galleries')
	images = models.ImageField(verbose_name='تصویر', upload_to='product/galleries/')

	def __str__(self):
		return self.product.title

	class Meta:
		verbose_name = 'گالری'
		verbose_name_plural = 'گالری ها'


# *********************** Section for model Product ***********************
@receiver(pre_save, sender=Product)
def pre_save_product(sender, instance, **kwargs):

	# ********** Section resize image ***********
	image = Image.open(instance.image)
	resized_image = image.resize((400, 400))
	fileName = "%s.%s" % (uuid4(), image.format)
	filePath = f"{settings.MEDIA_ROOT}/product/images/{fileName}"
	instance.thumbnail = f"product/images/{fileName}"
	resized_image.save(filePath)

	# ********** this section for remove old image ***************
	print(instance.pk)
	if instance.pk:
		try:
			old_product_image = Product.objects.get(pk=instance.pk).image
			old_product_thumbnail = Product.objects.get(pk=instance.pk).thumbnail
		except Product.DoesNotExist:
			return False

		new_product_image = instance.image
		new_product_thumbnail = instance.thumbnail
		print(new_product_image)
		print(new_product_thumbnail)
		if old_product_image and old_product_image.url != new_product_image.url and old_product_thumbnail \
			and old_product_thumbnail.url != new_product_thumbnail.url:
			os.remove(old_product_image.path)
			os.remove(old_product_thumbnail.path)

@receiver(pre_delete, sender=Product)
def pre_delete_product(sender, instance, **kwargs):
	object_current = sender.objects.get(pk=instance.pk)

	if object_current:
		os.remove(object_current.image.path)
		os.remove(object_current.thumbnail.path)


# *********************** Section for model GalleryProduct ***********************
@receiver(pre_delete, sender=GalleryProduct)
def pre_delete_gallery_product(sender, instance, **kwargs):
	object_current = sender.objects.get(pk=instance.pk)

	if object_current:
		os.remove(object_current.images.path)


@receiver(pre_save, sender=GalleryProduct)
def pre_save_gallery_product(sender, instance, **kwargs):

	if instance.pk:
		try:
			old_gallery_image = GalleryProduct.objects.get(pk=instance.pk).images
		except GalleryProduct.DoesNotExist:
			return False

		new_gallery_image = instance.images
		if old_gallery_image and old_gallery_image.url != new_gallery_image.url:
			os.remove(old_gallery_image.path)

shop/product/forms.py
from django import forms
from .models import Product, GalleryProduct


class ProductForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	class Meta:
		model = Product
		fields = ('title', 'text', 'price', 'discount', 'image', 'stock_count')

	def clean_discount(self):
		price = self.cleaned_data.get('price')
		discount = self.cleaned_data.get('discount')

		if discount < price:
			return discount
		raise forms.ValidationError('قیمت با تخفیف باید از قیمت اصلی محصول کوچک تر باشد.')

	def clean_price(self):
		price = self.cleaned_data.get('price')
		if price < 0 or price == 0:
			raise forms.ValidationError('لطفا یک قیمت درست وارد کنید.')

		return price

	def clean_stock_count(self):
		stock_count = self.cleaned_data.get('stock_count')
		if stock_count == 0 or stock_count < 0:
			raise forms.ValidationError('لطفا تعداد موجودی درست وارد نمایید.')

		return stock_count


class GalleryProductForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	image = forms.FileField(
		widget=forms.ClearableFileInput(attrs={
			'multiple': True
		}),
		required=True
	)

	class Meta:
		model = GalleryProduct
		fields = ('product', 'image')


class GalleryUpdateProductForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

	class Meta:
		model = GalleryProduct
		fields = ('product', 'images')

shop/product/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.forms import inlineformset_factory, formset_factory, modelformset_factory
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
	ListView,
	CreateView,
	UpdateView,
	DeleteView,
	DetailView,
)
from .models import Product, GalleryProduct
from .forms import ProductForm, GalleryProductForm, GalleryUpdateProductForm
from order.forms import AddToOrderForm
from order.models import Order, OrderDetail


# ********************* Section for Product Model *********************
class ProductListHomeView(ListView):
	model = Product
	template_name = 'product/product_list.html'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		
		if self.request.user.is_authenticated:
			order = Order.objects.filter(owner_id=self.request.user.id, is_paid=False).first()
			if order is not None:
				count = order.orderdetail_set.count()
				self.request.session['count'] = count
				if count > 0:
					if self.request.session.has_key('count'):
						self.request.session['count'] = count
					else:
						self.request.session['count'] = 0
				self.request.session['count'] = count
						
				context['count'] = count

		return context


class ProductDetailView(DetailView):
	model = Product
	template_name = 'product/product_detail.html'
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		# check count items
		if self.request.user.is_authenticated:
			order = Order.objects.filter(owner_id=self.request.user.id, is_paid=False).first()
			if order is not None:
				count = order.orderdetail_set.count()
				self.request.session['count'] = count
				if count > 0:
					if self.request.session.has_key('count'):
						self.request.session['count'] = count
					else:
						self.request.session['count'] = 0
				self.request.session['count'] = count

		product = kwargs.get('object')
		context['order_form'] = AddToOrderForm(self.request.POST or None, initial={'product_id': product.id, 'count': 1})
		return context


class ProductCreateView(LoginRequiredMixin, CreateView):
	model = Product
	form_class = ProductForm
	template_name = 'product/product_create.html'

	def form_valid(self, form):
		response = form.save(commit=False)
		context = {
			'form': form
		}
		if form.is_valid():
			title = form.cleaned_data.get('title')
			text = form.cleaned_data.get('text')
			image = form.cleaned_data.get('image')
			price = form.cleaned_data.get('price')
			discount = form.cleaned_data.get('discount')
			stock_count = form.cleaned_data.get('stock_count')

			Product.objects.create(
				title=title,
				text=text,
				image=image,
				price=price,
				discount=discount,
				stock_count=stock_count
			)
			messages.add_message(self.request, messages.SUCCESS, 'محصول شما با موفقیت ایجاد شد.')

		return render(self.request, self.template_name, context)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
	model = Product
	form_class = ProductForm
	template_name = 'product/product_create.html'
	success_url = reverse_lazy('product:home')


class ProductDeleteView(LoginRequiredMixin, DeleteView):
	model = Product
	template_name = 'product/product_confirm_delete.html'
	success_url = reverse_lazy('product:product_list')


class ProductListView(LoginRequiredMixin, ListView):
	model = Product
	template_name = 'product/list_product.html'


# ********************* Section for Gallery Model *********************
class GalleryListView(LoginRequiredMixin, ListView):
	model = GalleryProduct
	template_name = 'gallery/gallery_list.html'


class GalleryCreateView(LoginRequiredMixin, CreateView):
	model = GalleryProduct
	form_class = GalleryProductForm
	template_name = 'gallery/gallery_create.html'

	def post(self, request, *args, **kwargs):
		form_class = self.form_class
		form = self.get_form(form_class)
		context = {
			'form': form
		}

		if form.is_valid():
			product = form.cleaned_data.get('product')
			images = request.FILES.getlist('image')
			for image in images:
				GalleryProduct.objects.create(
					product=product,
					images=image
				)
			messages.add_message(request, messages.SUCCESS, 'گالری شما با موفقیت ایجاد شد.')
			print(product)
			print(images)

		return render(request, self.template_name, context)


class GalleryUpdateView(LoginRequiredMixin, UpdateView):
	model = GalleryProduct
	form_class = GalleryUpdateProductForm
	template_name = 'gallery/gallery_update.html'
	success_url = reverse_lazy('product:home')


class GalleryDeleteView(LoginRequiredMixin, DeleteView):
	model = GalleryProduct
	success_url = reverse_lazy('product:gallery_list')
	template_name = 'gallery/galleryproduct_confirm_delete.html'

shop/product/templates/gallery/gallery_create.html
{% extends 'product/base.html' %}

{% block title %} ساخت گالری برای محصولات | مدیریت فروشگاه {% endblock %}

{% block content %}
<!-- Product section-->
<section class="py-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="fw-bolder text-center text-info mb-5">ساخت گالری برای محصولات سایت</h1>
                <hr>
                {% include 'product/_messages.html' %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">

                        <div class="col-12 mb-3">
                            <label for="{{ form.product.id_for_label }}" class="form-label"> محصول مورد نظر انتخاب کنید: </label>
                            {{ form.product }}
                            {{ form.product.errors }}
                        </div>
                        <div class="col-12 mb-3">
                            <label for="{{ form.image.id_for_label }}" class="form-label">قیمت با تخفیف محصول: </label>
                            {{ form.image }}
                            <small class="text-form">شما میتوانید برای محصول خود چند تا عکس همزمان انتخاب کنید</small>
                            {{ form.image.errors }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">ذخیره</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/product/templates/gallery/gallery_list.html
{% extends 'product/base.html' %}

{% block title %} لیست گالری ها | مدیریت فروشگاه {% endblock %}

{% block content %}
<!-- Product section-->
<section class="py-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="fw-bolder text-center text-info mb-5">همه ای گالیر ای های سایت</h1>
                <hr>
                {% include 'product/_messages.html' %}
                <ul class="list">
                    {% for gallery in object_list %}
                        <li class="mb-3">
                            <a href="{% url 'product:gallery_update' gallery.pk %}">{{ gallery }}</a> -
                            <a href="{% url 'product:gallery_delete' gallery.pk %}" class="btn btn-danger btn-sm">حذف کردن</a>
                            <a href="{% url 'product:gallery_update' gallery.pk %}" class="btn btn-primary btn-sm">ویرایش</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/product/templates/gallery/gallery_update.html
{% extends 'product/base.html' %}

{% block title %} ویرایش گالری برای محصولات | مدیریت فروشگاه {% endblock %}

{% block content %}
<!-- Product section-->
<section class="py-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="fw-bolder text-center text-info mb-5">ویرایش گالری برای محصولات</h1>
                <hr>
                {% include 'product/_messages.html' %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.management_data }}
                    <div class="row">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary w-100">ویرایش کن</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/product/templates/gallery/galleryproduct_confirm_delete.html
<form method="post">{% csrf_token %}

<p>آیا از حذف این گالری تصویر مطمئن هستید ؟ "{{ object }}"?</p>

    <input type="submit" value="تایئد">
</form>